### ISSUE TITLE
aws_setup script requires some fixes

### ISSUE THREAD

**Issue by odockal** [adrianriobo/qenvs#180]
first thing is hardcoded crcqe user name. 
Other is not locally created access_info_key due to a misplaced double quote.
Third seems to be that after fixing two above, the access_key_info file contains some additional character that are not parsable with a jq command.

ie:
```
[?1h=
{[m
    "AccessKey": {[m
        "UserName": "my user name",[m
        "AccessKeyId": "yyy",[m
        "Status": "Active",[m
        "SecretAccessKey": "xxx",[m
        "CreateDate": "2023-12-20T19:05:39+00:00"[m
    }[m
}[m

[K[?1l>
```

**Comment by adrianriobo** [comment]
Fixed by #181
